# Generated by Django 4.0.6 on 2022-07-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_slug_alter_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
