# Generated by Django 4.1 on 2022-08-07 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_price_product_unit_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['customer']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order_id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title', 'unit_price']},
        ),
    ]
